
 drop table CP_BNCR033;
CREATE TABLE CP_BNCR033
(
	CSTDYRM_ID            VARCHAR2(10)  NOT NULL ,
	MANAGE_DEPT_CD        VARCHAR2(4)  NULL ,
	BULD_NM               VARCHAR2(50)  NULL ,
	RM_NO                 VARCHAR2(50)  NULL ,
	ZONE_NM               VARCHAR2(50)  NULL ,
	COLROW                VARCHAR2(50)  NULL ,
	RACK_MG               VARCHAR2(50)  NULL ,
	SGNFC                 VARCHAR2(50)  NULL 
);

  
ALTER TABLE CP_BNCR033
	ADD CONSTRAINT  PK_CP_BNCR033 PRIMARY KEY (CSTDYRM_ID);

COMMENT ON TABLE CP_BNCR033 IS '시료보관실기본';
 
    COMMENT ON COLUMN CP_BNCR033.CSTDYRM_ID IS '보관실 ID';   
    COMMENT ON COLUMN CP_BNCR033.SGNFC IS '특이사항';   
    COMMENT ON COLUMN CP_BNCR033.RACK_MG IS '렉 크기';   
    COMMENT ON COLUMN CP_BNCR033.COLROW IS '행단';   
    COMMENT ON COLUMN CP_BNCR033.ZONE_NM IS '구역 명';   
    COMMENT ON COLUMN CP_BNCR033.RM_NO IS '실 번호';   
    COMMENT ON COLUMN CP_BNCR033.BULD_NM IS '건물 명';   
    COMMENT ON COLUMN CP_BNCR033.MANAGE_DEPT_CD IS '관리 부서 코드';   
	
	 
drop table CP_BNCR019;

CREATE TABLE CP_BNCR019
(
	SPLORE_LBL_ID         VARCHAR2(10)  NOT NULL ,
	REGISTER_ID           VARCHAR2(10)  NOT NULL ,
	REGIST_DT             DATE  NOT NULL ,
	CHANGER_ID            VARCHAR2(10)  NOT NULL ,
	CHANGE_DT             DATE  NOT NULL ,
	SPLORE_LAST_PROC_SE_CD  VARCHAR2(1)  NULL ,
	SPLORE_RETURN_DE      VARCHAR2(8)  NULL ,
	SPLORE_ATCH_ID        VARCHAR2(6)  NULL ,
	ISSU_DE               VARCHAR2(8)  NULL ,
	CSTDY_END_DE          VARCHAR2(8)  NULL ,
	ARVL_DEPT_CD          VARCHAR2(4)  NOT NULL ,
	RCEPT_ID              VARCHAR2(10)  NOT NULL ,
	USE_YN                VARCHAR2(1)  NOT NULL ,
	START_DEPT_CD         VARCHAR2(4)  NOT NULL ,
	START_SPORT_HDQR_CD   VARCHAR2(4)  NULL ,
	ARVL_SPORT_HDQR_CD    VARCHAR2(4)  NULL 
);



ALTER TABLE CP_BNCR019
	ADD CONSTRAINT  PK_CP_BNCR019 PRIMARY KEY (SPLORE_LBL_ID,RCEPT_ID);


   
COMMENT ON TABLE CP_BNCR019 IS '시료라벨기본';
 
    COMMENT ON COLUMN CP_BNCR019.SPLORE_LBL_ID IS '시료 라벨 ID';   
    COMMENT ON COLUMN CP_BNCR019.RCEPT_ID IS '접수 ID';   
    COMMENT ON COLUMN CP_BNCR019.SPLORE_LAST_PROC_SE_CD IS '시료 최종 처리 구분 코드';   
    COMMENT ON COLUMN CP_BNCR019.SPLORE_RETURN_DE IS '시료 반환 일자';   
    COMMENT ON COLUMN CP_BNCR019.SPLORE_ATCH_ID IS '시료 첨부 ID';   
    COMMENT ON COLUMN CP_BNCR019.REGISTER_ID IS '시료첨부 ID
  ';   
    COMMENT ON COLUMN CP_BNCR019.REGIST_DT IS '발급일자';   
    COMMENT ON COLUMN CP_BNCR019.CHANGER_ID IS '출발부서코드';   
    COMMENT ON COLUMN CP_BNCR019.CHANGE_DT IS '변경 일시';   
    COMMENT ON COLUMN CP_BNCR019.ISSU_DE IS '발급 일자';   
    COMMENT ON COLUMN CP_BNCR019.CSTDY_END_DE IS '보관 종료 일자';   
    COMMENT ON COLUMN CP_BNCR019.ARVL_DEPT_CD IS '도착 부서 코드';   
    COMMENT ON COLUMN CP_BNCR019.USE_YN IS '사용 여부';   
    COMMENT ON COLUMN CP_BNCR019.START_DEPT_CD IS '출발 부서 코드';   
    COMMENT ON COLUMN CP_BNCR019.START_SPORT_HDQR_CD IS '출발 지원 본부 코드';   
    COMMENT ON COLUMN CP_BNCR019.ARVL_SPORT_HDQR_CD IS '도착 지원 본부 코드';   
    	
	 
drop table CP_BNCR020;

CREATE TABLE CP_BNCR020
(
	MVMN_TAG_ID           NUMBER(2)  NOT NULL ,
	TAG_PROC_DT           DATE  NOT NULL ,
	REGISTER_ID           VARCHAR2(10)  NOT NULL ,
	REGIST_DT             DATE  NOT NULL ,
	CHANGER_ID            VARCHAR2(10)  NOT NULL ,
	CHANGE_DT             DATE  NOT NULL ,
	SPLORE_LBL_ID         VARCHAR2(10)  NOT NULL ,
	TAG_OPETR_ID          VARCHAR2(10)  NOT NULL ,
	TAG_PURPS_CD          VARCHAR2(2)  NULL ,
	RETURN_SE_CD          VARCHAR2(2)  NULL ,
	NEXT_ARVL_DEPT_CD     VARCHAR2(4)  NULL ,
	NEXT_ARVL_CHARGER_ID  VARCHAR2(10)  NULL ,
	TAG_PROC_DEPT         VARCHAR2(4)  NOT NULL ,
	RCEPT_ID              VARCHAR2(10)  NOT NULL ,
	CSTDY_END_DE          VARCHAR2(8)  NULL ,
	SPLORE_RETURN_DE      VARCHAR2(8)  NULL ,
	CSTDYRM_ID            VARCHAR2(10)  NULL 
);


 


ALTER TABLE CP_BNCR020
	ADD CONSTRAINT  PK_CP_BNCR020 PRIMARY KEY (MVMN_TAG_ID,SPLORE_LBL_ID);

	
COMMENT ON TABLE CP_BNCR020 IS '이동태그기본';

COMMENT ON COLUMN CP_BNCR020.MVMN_TAG_ID IS '이동 태그 ID';
COMMENT ON COLUMN CP_BNCR020.CSTDYRM_ID IS '보관실 ID';
COMMENT ON COLUMN CP_BNCR020.SPLORE_LBL_ID IS '시료 라벨 ID';
COMMENT ON COLUMN CP_BNCR020.TAG_OPETR_ID IS '태그 처리자 ID';
COMMENT ON COLUMN CP_BNCR020.TAG_PURPS_CD IS '태그 목적 코드';
COMMENT ON COLUMN CP_BNCR020.TAG_PROC_DT IS '태그 처리 일시';
COMMENT ON COLUMN CP_BNCR020.RETURN_SE_CD IS '반환 구분 코드';
COMMENT ON COLUMN CP_BNCR020.REGISTER_ID IS '등록자 ID';
COMMENT ON COLUMN CP_BNCR020.REGIST_DT IS '등록 일시';
COMMENT ON COLUMN CP_BNCR020.CHANGER_ID IS '변경자 ID';
COMMENT ON COLUMN CP_BNCR020.CHANGE_DT IS '변경 일시';
COMMENT ON COLUMN CP_BNCR020.NEXT_ARVL_DEPT_CD IS '다음 도착 부서 코드';
COMMENT ON COLUMN CP_BNCR020.NEXT_ARVL_CHARGER_ID IS '다음 도착 담당자 ID';
COMMENT ON COLUMN CP_BNCR020.TAG_PROC_DEPT IS '태그 처리 부서';
COMMENT ON COLUMN CP_BNCR020.RCEPT_ID IS '접수 ID';
COMMENT ON COLUMN CP_BNCR020.CSTDY_END_DE IS '보관 종료 일자';
COMMENT ON COLUMN CP_BNCR020.SPLORE_RETURN_DE IS '시료 반환 일자';


drop table CP_BNCR034;  
  
CREATE TABLE CP_BNCR034
(
	NOW_VER               VARCHAR2(15)  NOT NULL ,
	DETAIL_VER            VARCHAR2(15)  NULL ,
	REFLCT_DT             DATE  NOT NULL ,
	DOWNLOAD_URL          VARCHAR2(200)  NULL ,
	USE_YN                VARCHAR2(1)  NOT NULL 
);


 
ALTER TABLE CP_BNCR034
	ADD CONSTRAINT  PK_CP_BNCR034 PRIMARY KEY (NOW_VER);



	
    
COMMENT ON TABLE CP_BNCR034 IS '시료관리앱버전';
 
    COMMENT ON COLUMN CP_BNCR034.NOW_VER IS '현재 버전';   
    COMMENT ON COLUMN CP_BNCR034.USE_YN IS '사용 여부';   
    COMMENT ON COLUMN CP_BNCR034.DOWNLOAD_URL IS '다운로드 URL';   
    COMMENT ON COLUMN CP_BNCR034.REFLCT_DT IS '반영 일시';   
    COMMENT ON COLUMN CP_BNCR034.DETAIL_VER IS '상세 버전';   

 
drop table CP_BNCR035;

CREATE TABLE CP_BNCR035
(
	SN                    INTEGER  NOT NULL ,
	CONECTR_ID            VARCHAR2(10)  NOT NULL ,
	SERIAL_NO             NVARCHAR2(50)  NOT NULL ,
	CONECT_DT             DATE  NOT NULL 
);

 

ALTER TABLE CP_BNCR035
	ADD CONSTRAINT  PK_CP_BNCR035 PRIMARY KEY (SN);

  
  
COMMENT ON TABLE CP_BNCR035 IS '시료관리접속이력';
 
    COMMENT ON COLUMN CP_BNCR035.SN IS '순번';   
    COMMENT ON COLUMN CP_BNCR035.CONECTR_ID IS '접속자 ID';   
    COMMENT ON COLUMN CP_BNCR035.SERIAL_NO IS '시리얼 번호';   
    COMMENT ON COLUMN CP_BNCR035.CONECT_DT IS '접속 일시';   
    	
	
	
	
	
	
	
	